app/urls.py
from django.urls import path
from . import views


app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('check_email/<str:email>/', views.check_email, name='check_email'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('wall/', views.wall, name='wall'),
    path('messages/create/', views.create_message, name='create_message'),
    path('messages/<int:message_id>/destroy/', views.destroy_message, name='destroy_message'),
    path('comments/create', views.create_comment, name='create_comment'),
    path('comments/<int:comment_id>/destroy/', views.destroy_comment, name='destroy_comment'),
    path('logout/', views.logout, name='logout')
]

django_wall/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    # path('admin/', admin.site.urls),
]

app/models.py
from django.db import models
import bcrypt


class BaseModel(models.Model):
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)


class UserManager(models.Manager):
  def validate(self, postData):
    errors = {}
    fn = postData['first_name']
    ln = postData['last_name']
    em = postData['email']
    if len(fn) < 2:
      errors['first_name'] = 'First name must be 2 or more characters'
    elif len(fn) > 45:
      errors['first_name'] = 'First name must be 45 or less characters'
    if len(ln) < 2:
      errors['last_name'] = 'Last name must be 2 or more characters'
    elif len(ln) > 45:
      errors['last_name'] = 'Last name must be 45 or less characters'
    if len(User.objects.filter(email=em)) > 0:
      errors['last_name'] = 'User with email already exists please login'
    if len(postData['pw']) < 8:
      errors['pw'] = 'Password must be 8 or more characters'
    elif len(postData['pw']) >255:
      errors['pw'] = 'Password must be 255 or less characters'
    if postData['pw'] != postData['pw_confirm']:
      errors['pw'] = 'Passwords must match'
    return errors

  def gen_token(self, user_id):
    user = self.get(id=user_id)
    string = user.last_name + user.email + str(user.created_at)
    return bcrypt.hashpw(string.encode(), bcrypt.gensalt()).decode()

  def is_user_authenticated(self, user_id, token):
    try:
      user = self.get(id=user_id)
    except User.DoesNotExist:
      return False
    string = user.last_name + user.email + str(user.created_at)
    return bcrypt.checkpw(
      string.encode(),
      self.gen_token(user_id).encode()
    )


class User(BaseModel):
  first_name = models.CharField(max_length=255)
  last_name = models.CharField(max_length=255)
  email = models.CharField(max_length=255)
  pw_hash = models.CharField(max_length=255)
  objects = UserManager()

  def __str__(self):
    return f'User {self.first_name} {self.last_name}'


class Message(BaseModel):
  owner = models.ForeignKey(
    User, on_delete=models.CASCADE, related_name='messages')
  text = models.TextField()

  def __str__(self):
    return f'Message {self.id}'


class Comment(BaseModel):
  on_message = models.ForeignKey(
    Message, on_delete=models.CASCADE, related_name='comments')
  owner = models.ForeignKey(
    User, on_delete=models.CASCADE, related_name='comments')
  text = models.TextField()

  def __str__(self):
    return f'Comment {self.id} on {self.message_id}'

app/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from django.contrib import messages
import bcrypt

from app.models import User, Message, Comment

# Default route to login or register
def index(request):
  return render(request, 'index.html')

# POST route to login an existing user
def login(request):
  if request.method == 'POST':
    if 'login_err' in request.session:
      del request.session['login_err']
    if not 'login_attempts' in request.session:
      request.session['login_attempts'] = 1
    else:
      request.session['login_attempts'] += 1
    users = User.objects.filter(email=request.POST['email'])
    if users:
      user = users[0]
      if bcrypt.checkpw(request.POST['pw'].encode(), user.pw_hash.encode()):
        request.session['user_id'] = user.id
        request.session['user_name'] = user.first_name
        request.session['token'] = User.objects.gen_token(user.id)
        return redirect(reverse('app:wall'))

    request.session['login_err'] = True
    messages.error(
      request,
      f'Invalid credentials. {request.session["login_attempts"]} bad attempts.'
    )
  return redirect(reverse('app:index'))

# POST route to register a new user
def register(request):
  if request.method == 'POST':
    if 'reg_err' in request.session:
      del request.session['reg_err']
    errors = User.objects.validate(request.POST)
    if len(errors) == 0:
      user = User.objects.create(
        first_name=request.POST['first_name'],
        last_name=request.POST['last_name'],
        email=request.POST['email'],
        pw_hash=bcrypt.hashpw(
          request.POST['pw'].encode(), bcrypt.gensalt()).decode()
      )
      request.session['user_id'] = user.id
      request.session['user_name'] = user.first_name
      request.session['token'] = User.objects.gen_token(user.id)
      return redirect(reverse('app:wall'))

    request.session['reg_err'] = True
    for key, value in errors.items():
      messages.error(request, value)
  return redirect(reverse('app:index'))

# GET route for a logged in user
def wall(request):
  is_auth = User.objects.is_user_authenticated(
    request.session['user_id'],
    request.session['token']
  )
  if is_auth:
    context = {
      'messages': Message.objects.all().order_by('-created_at')
    }
    return render(request, 'wall.html', context)
  return redirect(reverse('app:index'))

# POST route for creating a new message
def create_message(request):
  if request.method == 'POST':
    user_id = request.session['user_id']
    is_auth = User.objects.is_user_authenticated(
      user_id,
      request.session['token']
    )
    if is_auth:
      Message.objects.create(
        owner = User.objects.get(id=user_id),
        text = request.POST['message_text']
      )
  return redirect(reverse('app:wall'))

# POST route for deleting a message for logged in user
def destroy_message(request, message_id):
  if request.method == 'POST':
    user_id = request.session['user_id']
    is_auth = User.objects.is_user_authenticated(
      user_id,
      request.session['token']
    )
    try:
      message = Message.objects.get(id=message_id)
    except Message.DoesNotExist:
      return HttpResponse('Message does not exist', status=404)
    if not is_auth or message.owner.id != user_id:
      return HttpResponse('This is not your message', status=401)

    message.delete()
  return redirect(reverse('app:wall'))

# POST route for creating a new comment on a message
def create_comment(request):
  if request.method == 'POST':
    user_id = request.session['user_id']
    message = Message.objects.get(id=request.POST['message_id'])
    is_auth = User.objects.is_user_authenticated(
      user_id,
      request.session['token']
    )
    if is_auth:
      Comment.objects.create(
        owner = User.objects.get(id=user_id),
        on_message = message,
        text = request.POST['comment_text']
      )
  return redirect(reverse('app:wall'))

# POST route for deleting a comment for logged in user
def destroy_comment(request, comment_id):
  if request.method == 'POST':
    user_id = request.session['user_id']
    is_auth = User.objects.is_user_authenticated(
      user_id,
      request.session['token']
    )
    try:
      comment = Comment.objects.get(id=comment_id)
    except Comment.DoesNotExist:
      return HttpResponse('Comment does not exist', status=404)
    if not is_auth or comment.owner.id != user_id:
      return HttpResponse('This is not your message', status=401)

    comment.delete()
  return redirect(reverse('app:wall'))

# GET route for logging out a user
def logout(request):
  request.session.clear()
  return redirect(reverse('app:index'))

# GET route for checking email availability, sends 'available' or 'unavailable'
def check_email(request, email):
  if len(User.objects.filter(email=email)) == 0:
    return HttpResponse('available')
  return HttpResponse('unavailable')

app/templates/index.html
<!--
  Author: Justin Clayton
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
  <header class="text-light">
    <h1>Coding Dojo Wall</h1>
  </header>
  <main class="container bg-light text-center">
    <div class="row">
      <form class="col-lg-5" action="{% url 'app:login' %}" method="POST">
        {% csrf_token %}
        <h2>Log In</h2>

        {% if messages and 'login_err' in request.session %}
          {% for message in messages %}
            <p class="text-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Email:</span>
          </div>
          <input name="email" type="email" class="form-control" minlength="2"
            maxlength="255" required>
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Password:</span>
          </div>
          <input name="pw" type="password" class="form-control"
            minlength="8" required>
        </div>

        <button type="submit" class="btn btn-primary">Log In</button>
      </form>

      <form class="col-lg-5" action="{% url 'app:register' %}" method="POST">
        {% csrf_token %}
        <h2>Registration</h2>

        {% if messages and 'reg_err' in request.session %}
          {% for message in messages %}
            <p class="text-danger">{{ message }}</p>
          {% endfor %}
        {% endif %}

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">First Name:</span>
          </div>
          <input name="first_name" id="first_name" type="text" required
            class="form-control">
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Last Name:</span>
          </div>
          <input name="last_name" id="last_name" type="text" required
            class="form-control">
        </div>

        <p id='email-valid' class="hidden"></p>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Email:</span>
          </div>
          <input name="email" id="email" type="email" class="form-control"
            minlength="2" maxlength="255" required>
        </div>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Password:</span>
          </div>
          <input name="pw" id="pw" type="password" class="form-control"
            minlength="8" required>
        </div>

        <p id='pw-valid' class="hidden"></p>

        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Confirm PW:</span>
          </div>
          <input name="pw_confirm" id="pw_confirm" type="password"
            class="form-control" minlength="8" required>
        </div>

        <button type="submit" class="btn btn-primary">Register</button>
      </form>
    </div>
  </main>
</body>
</html>

app/templates/wall.html
<!--
  Author: Justin Clayton
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>The Wall</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
    crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'js/index.js' %}"></script>
</head>
<body>
  <header class="text-light">
    <h1>Coding Dojo Wall</h1>
    <p>
      Welcome {{ request.session.user_name }}
      <a class="btn btn-warning" href="{% url 'app:logout' %}">Logout</a>
    </p>
  </header>
  <div class="container bg-light">
    <h2>Create a New Message</h2>
    <form action="{% url 'app:create_message' %}" method="POST">{% csrf_token %}
      <textarea name="message_text" class="form-control" required></textarea>
      <button type="submit" class="btn btn-primary">Post</button>
    </form>
    <section id="messages">
      {% for message in messages %}
      <div class="message">
        <h3>
          <div>
            {{ message.owner.first_name }} {{ message.owner.last_name }} -
            {{ message.created_at }}
          </div>
          {% if message.owner.id == request.session.user_id %}
          <form action="{% url 'app:destroy_message' message_id=message.id %}"
            method="POST">{% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
          {% endif %}
        </h3>
        <p>
          {{ message.text }}
        </p>
        <div id="comments">
          {% for comment in message.comments.all %}
          <h4>
            <div>
              {{ comment.owner.first_name }} {{ comment.owner.last_name }} -
              {{ comment.created_at }}
            </div>
            {% if comment.owner.id == request.session.user_id %}
            <form action="{% url 'app:destroy_comment' comment_id=comment.id %}"
              method="POST">{% csrf_token %}
              <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            {% endif %}
          </h4>
          <p> {{ comment.text }}</p>
          {% endfor %}
          <h4>Post a comment</h4>
          <form action="{% url 'app:create_comment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="message_id" value="{{ message.id }}">
            <textarea name="comment_text" class="form-control" required></textarea>
            <button type="submit" class="btn btn-success">Post</button>
          </form>
        </div>
      </div>
      {% endfor %}
    </section>
  </div>
</body>
</html>